POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento", 
  "details": "Detalhes do evento", 
  "maximunAttendees": 1
}

###
POST http://localhost:3333/events/aaddbacd-6087-43f6-b82b-d32ca2908b84/attendees
Content-Type: application/json

{
  "name": "Maria tereza de Jesus", 
  "email": "maria@gmail.com"
}