POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Com o slug", 
  "details": "com slug", 
  "maximunAttendees": 100
}

###
POST http://localhost:3333/events/fdc2ce66-731f-41fd-821c-8fdfc4f1caf5/attendees
Content-Type: application/json

{
  "name": "Robson de Jesus", 
  "email": "robson@gmail.com"
}